application: pickafoood09081993
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: static/\1
  upload: static/(.*\.eot)

- url: /img
  static_dir: img

- url: /static
  static_dir: static

- url: /.*
  script: start.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
